AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  List processes inside the Lambda container

Resources:
  PSFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ps
      CodeUri: ./
      Handler: ps
      Runtime: go1.x
      MemorySize: 128
      Timeout: 30
      Tracing:
        Active
